name: insert_coin
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  saf: ^1.0.4
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  flutter_svg: ^2.0.9

  # device_apps removed temporarily to avoid AGP namespace issue; re-add when fixed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7

# flutter_native_splash:
#   android: true
#   ios: false
#   image_path: 'lib/assets/favicon.png'

flutter_native_splash:
  color: '#1E1E1E' # même couleur que adaptive_icon_background
  image: 'lib/assets/favicon.png' # optionnel, petit logo centré (sans fond)
  android_12:
    color: '#1E1E1E'
    icon_background_color: '#1E1E1E' # si tu mets une icône

flutter:
  uses-material-design: true
  assets:
    - lib/assets/apps/
    - lib/assets/icons/
    - lib/assets/favicon.png
